config/routes.rb
Rails.application.routes.draw do
  resources :chickens
  resources :dashboards
  resources :comments
  resources :blogs
  devise_for :users
  resources :contacts
  resources :abouts
  resources :homes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "homes#index"
end

app/models/chicken.rb
class Chicken < ApplicationRecord
  # Custom slug config here
  extend FriendlyId
  friendly_id :tag_number, use: :slugged

  def to_param
    slug
  end
  
  # Associations
  belongs_to :user
  has_one_attached :chicken_image

  # Callback for custom methods
  before_create :generate_tag_number
  before_create :calculate_age

  private

  def generate_tag_number
    # Get the corrent month eh June
    current_month = Date.today.strftime('%B')

    # Get the current date in the month
    current_date = Date.today.strftime('%d')

    id = Chicken.count + 1

    # Let's append a few zeros before the ID of the record being created
    tag_number_with_zeros = format('%03d', id)

    # Now let's wire them all up together
    self.tag_number = "#{current_month}#{current_date}#{tag_number_with_zeros}"
  end

  def calculate_age
    if date_hatched.present?
      days_old = (Date.today - date_hatched.to_date).to_i
      age_in_weeks = (days_old / 7.0)
      self.age = age_in_weeks.round(2)
    else
      self.age = nil
    end
  end

end

app/controllers/chickens_controller.rb
class ChickensController < ApplicationController
  before_action :set_chicken, only: %i[ show edit update destroy ]

  # GET /chickens or /chickens.json
  def index
    @chickens = Chicken.all
  end

  # GET /chickens/1 or /chickens/1.json
  def show
    @chicken = Chicken.friendly.find(params[:id])
  end

  # GET /chickens/new
  def new
    @chicken = Chicken.new
  end

  # GET /chickens/1/edit
  def edit
  end

  # POST /chickens or /chickens.json
  def create
    @chicken = Chicken.new(chicken_params)

    respond_to do |format|
      if @chicken.save
        format.html { redirect_to chicken_url(@chicken), notice: "Chicken was successfully created." }
        format.json { render :show, status: :created, location: @chicken }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chicken.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chickens/1 or /chickens/1.json
  def update
    respond_to do |format|
      if @chicken.update(chicken_params)
        format.html { redirect_to chicken_url(@chicken), notice: "Chicken was successfully updated." }
        format.json { render :show, status: :ok, location: @chicken }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chicken.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chickens/1 or /chickens/1.json
  def destroy
    @chicken.destroy

    respond_to do |format|
      format.html { redirect_to chickens_url, notice: "Chicken was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chicken
      @chicken = Chicken.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chicken_params
      params.require(:chicken).permit(:tag_number, :age, :date_hatched, :parent_id, :user_id, :chicken_image)
    end
end

app/helpers/chickens_helper.rb
module ChickensHelper
end

app/views/chickens/_form.html.erb
<%= form_with(model: chicken) do |form| %>
  <% if chicken.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chicken.errors.count, "error") %> prohibited this chicken from being saved:</h2>

      <ul>
        <% chicken.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tag_number, style: "display: block" %>
    <%= form.text_field :tag_number %>
  </div>

  <div>
    <%= form.label :chicken_images, style: "display: block" %>
    <%= form.file_field :chicken_images, multiple: true, direct_upload: true %>
    <div id="image-preview"></div>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :date_hatched, style: "display: block" %>
    <%= form.date_field :date_hatched %>
  </div>

  <div>
    <%= form.label :parent_id, style: "display: block" %>
    <%= form.number_field :parent_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chickens/edit.html.erb
<h1>Editing chicken</h1>

<%= render "form", chicken: @chicken %>

<br>

<div>
  <%= link_to "Show this chicken", @chicken %> |
  <%= link_to "Back to chickens", chickens_path %>
</div>

app/views/chickens/index.html.erb
<p style="color: green"><%= notice %></p>

<header class="aboutheader">
  <h2>Chickens</h2>
  <h3><%= link_to "Home", root_path %> <span>-</span>Chickens</h3>
</header>

<main class="chickens">
  <% if user_signed_in? %>
    <div class="newchickenlink">
      <h2 class="darkgreentext">Let's create a new chicken</h2>
      <p><%= link_to "New Chicken", new_chicken_path %></p>
    </div>
  <% end %>
  <section class="chickensWrapper">
    <% if @chickens.empty? %>
      <h2>There are no created chickens yet</h2> 
    <% else %>
      <% @chickens.each do |chicken| %>
        <div class="chicken">
          <% if chicken.chicken_image.attached? %>
            <image src="<%= (url_for(chicken.chicken_image))%>">
          <% end %>

          <div>
            <p>
              <strong>Tag number:</strong>
              <%= chicken.tag_number %>
            </p>

            <p class="chickenlink">
              <%= link_to "CHICKEN DETAILS", chicken %>
              <i class="fa fa-arrow-right" aria-hidden="true"></i>
            </p>
          </div>
        </div>
      <% end %>
    <% end %>
  </section>

</main>

app/views/chickens/new.html.erb
<% if user_signed_in? %>
  <main class="chickensPage">
    <section class="newChicken">
      <div class="newChickenLeft">
        <h2>This side will be updated</h2>
      </div>

      <div class="newChickenRight">
        <%= form_with(model: @chicken) do |form| %>
          <% if @chicken.errors.any? %>
            <div style="color: red">
              <h2><%= pluralize(@chicken.errors.count, "error") %> prohibited this chicken from being saved:</h2>

              <ul>
                <% @chicken.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="blogform">
            <%= form.text_field :tag_number, type: :hidden %>
          </div>

          <div class="blogform">
            <%= form.label :chicken_image, style: "display: block" %>
            <%= form.file_field :chicken_image %>
            <div id="image-preview"></div>
          </div>

          <div class="blogform">
            <%= form.text_field :age, type: :hidden %>
          </div>

          <div class="blogform">
            <%= form.label :date_hatched, style: "display: block" %>
            <%= form.date_field :date_hatched %>
          </div>

          <div class="blogform">
            <%= form.label :parent_id, style: "display: block" %>
            <%= form.text_field :parent_id %>
          </div>

          <div>
            <%= form.number_field :user_id, id: :chicken_user_id, value: current_user.id, type: :hidden %>
          </div>

          <p>
            <%= form.submit %>
          </p>
        <% end %>
      </div>
    </section>
  </main>
<% else %>

  <main class="chickensPage">
    <p>Kindly login to create a chicken</p>
  </main>
<% end %>

app/views/chickens/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @chicken %>

<div>
  <%= link_to "Edit this chicken", edit_chicken_path(@chicken) %> |
  <%= link_to "Back to chickens", chickens_path %>

  <%= button_to "Destroy this chicken", @chicken, method: :delete %>
</div>