config/routes.rb
Rails.application.routes.draw do
  resources :chickens
  resources :dashboards
  resources :comments
  resources :blogs
  devise_for :users
  resources :contacts
  resources :abouts
  resources :homes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "homes#index"
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_dashboard, only: %i[show edit update destroy]

  # GET /dashboards or /dashboards.json
  def index
    @dashboards = Dashboard.all
  end

  # GET /dashboards/1 or /dashboards/1.json
  def show; end

  # GET /dashboards/new
  def new
    @dashboard = Dashboard.new
  end

  # GET /dashboards/1/edit
  def edit; end

  # POST /dashboards or /dashboards.json
  def create
    @dashboard = Dashboard.new(dashboard_params)

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to dashboard_url(@dashboard), notice: 'Dashboard was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboards/1 or /dashboards/1.json
  def update
    respond_to do |format|
      if @dashboard.update(dashboard_params)
        format.html { redirect_to dashboard_url(@dashboard), notice: 'Dashboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1 or /dashboards/1.json
  def destroy
    @dashboard.destroy

    respond_to do |format|
      format.html { redirect_to dashboards_url, notice: 'Dashboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_dashboard
    @dashboard = Dashboard.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def dashboard_params
    params.fetch(:dashboard, {})
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_dashboard.html.erb
<div id="<%= dom_id dashboard %>">
</div>

app/views/dashboards/_form.html.erb
<%= form_with(model: dashboard) do |form| %>
  <% if dashboard.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
        <% dashboard.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dashboards/edit.html.erb
<h1>Editing dashboard</h1>

<%= render "form", dashboard: @dashboard %>

<br>

<div>
  <%= link_to "Show this dashboard", @dashboard %> |
  <%= link_to "Back to dashboards", dashboards_path %>
</div>

app/views/dashboards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dashboards</h1>

<div id="dashboards">
  <% @dashboards.each do |dashboard| %>
    <%= render dashboard %>
    <p>
      <%= link_to "Show this dashboard", dashboard %>
    </p>
  <% end %>
</div>

<%= link_to "New dashboard", new_dashboard_path %>

app/views/dashboards/new.html.erb
<h1>New dashboard</h1>

<%= render "form", dashboard: @dashboard %>

<br>

<div>
  <%= link_to "Back to dashboards", dashboards_path %>
</div>

app/views/dashboards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dashboard %>

<div>
  <%= link_to "Edit this dashboard", edit_dashboard_path(@dashboard) %> |
  <%= link_to "Back to dashboards", dashboards_path %>

  <%= button_to "Destroy this dashboard", @dashboard, method: :delete %>
</div>