config/routes.rb
Rails.application.routes.draw do
  resources :chickens
  resources :dashboards
  resources :comments
  resources :blogs
  devise_for :users
  resources :contacts
  resources :abouts
  resources :homes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "homes#index"
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  # validations
  validates :blog_image, presence: true
  validates :blog_title, presence: true
  validates :blog_intro, presence: true
  validates :date_created, presence: true
  validates :comments_counter, presence: true, numericality: { only_integer: true }
  validates :blog_text, presence: true
  validates :user_id, presence: true, numericality: { only_integer: true }

  # Friendly for the custom slug
  extend FriendlyId
  friendly_id :blog_title, use: :slugged

  # associations

  belongs_to :user
  has_many :comments
  has_one_attached :blog_image
  after_save :update_blogs_counter

  def update_blogs_counter
    user.increment!(:blogs_counter)
  end

  def to_param
    slug
  end
end

app/models/chicken.rb
class Chicken < ApplicationRecord
  # Custom slug config here
  extend FriendlyId
  friendly_id :tag_number, use: :slugged

  def to_param
    slug
  end
  
  # Associations
  belongs_to :user
  has_one_attached :chicken_image

  # Callback for custom methods
  before_create :generate_tag_number
  before_create :calculate_age

  private

  def generate_tag_number
    # Get the corrent month eh June
    current_month = Date.today.strftime('%B')

    # Get the current date in the month
    current_date = Date.today.strftime('%d')

    id = Chicken.count + 1

    # Let's append a few zeros before the ID of the record being created
    tag_number_with_zeros = format('%03d', id)

    # Now let's wire them all up together
    self.tag_number = "#{current_month}#{current_date}#{tag_number_with_zeros}"
  end

  def calculate_age
    if date_hatched.present?
      days_old = (Date.today - date_hatched.to_date).to_i
      age_in_weeks = (days_old / 7.0)
      self.age = age_in_weeks.round(2)
    else
      self.age = nil
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  # validations
  validates :comment_text, presence: true
  validates :commenter_name, presence: true
  validates :blog_id, presence: true, numericality: { only_integer: true }

  # associations
  belongs_to :blog

  after_save :update_comments_counter

  def update_comments_counter
    blog.increment!(:comments_counter)
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # validations
  validates :names, presence: true, length: { minimum: 1, maximum: 50 }
  validates :email, presence: true
  validates :profile_photo, presence: true
  validates :role, presence: true
  validates :blogs_counter, presence: true, numericality: { only_integer: true }
  validates :mobile_number, presence: true, length: { is: 9 }, numericality: { only_integer: true }
  validates :status, presence: true
  validates :location, presence: true

  # associations

  has_one_attached :profile_photo
  has_many :blogs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index; end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @blog = Blog.friendly.find(params[:id])
    @paragraphs = @blog.blog_text.split('/')
    @comment = @blog.comments.build
    # @user = User.find_by(@post.user_id)
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit; end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def blog_params
    params.require(:blog).permit(:blog_image, :blog_title, :date_created, :comments_counter, :blog_text, :user_id,
                                 :blog_intro)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @blogs = Blog.order(created_at: :desc).limit(3)
    @images = {
      image1: 'farmimg1.jpg',
      image2: 'farmimg2.jpg',
      image3: 'farmimg3.jpg',
      image4: 'farmimg4.jpg',
      image5: 'farmimg5.jpg',
      image6: 'farmimg6.jpg',
      image7: 'farmimg7.jpg',
      image8: 'farmimg8.jpg'
    }
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/chickens_helper.rb
module ChickensHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <section class="footerWrapper">
    <div class="left">
      <h2>My <span>Kuku</span></h2>
      <p class="lightgraytext">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempora ad cumque, eveniet</p>
      <ul class="socials">
        <li><a href="https://github.com/Nemwel-Boniface" class="socisl-icons" target="_blank"><i class="fa fa-github" aria-hidden="true"></i></a></li>
        <li><a href="https://twitter.com/nemwel_bonie" class="socisl-icons" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
        <li><a href="http://instagram.com/its_n.e.m.w.e.l" class="socisl-icons" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
        <li><a href="https://www.linkedin.com/in/nemwel-nyandoro-aa1b2620b" class="socisl-icons" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
      </ul>
    </div>

    <div class="middle">
      <h2>Our <span>links</span></h2>
      <ul class="links">
        <li><i class="fa fa-chevron-right" aria-hidden="true"></i><%= link_to "Home", root_path, class: ""%></li>
        <li><i class="fa fa-chevron-right" aria-hidden="true"></i><%= link_to "About Us", abouts_path, class: ""%></li>
        <li><i class="fa fa-chevron-right" aria-hidden="true"></i><%= link_to "Contact Us", contacts_path, class: ""%></li>
        <li><i class="fa fa-chevron-right" aria-hidden="true"></i><%= link_to "Sign In", "#", class: ""%></li>
        <li><i class="fa fa-chevron-right" aria-hidden="true"></i><%= link_to "About Us", "#", class: ""%></li>
      </ul>
    </div>

    <div class="right">
      <h2>Newsletters</h2>
      <p class="lightgraytext">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempora ad cumque, eveniet</p>
      <form>
        <input type="email" placeholder="example@gmail.com" required>
        <button type="submit">SEND</button>
      </form>
    </div>
  </section>

  <div class="desgnedby">
    <p>Designed with <i class="fa fa-heart" aria-hidden="true"></i> By <a href="https://www.linkedin.com/in/nemwel-nyandoro" target="_blank">Nemwel.</a></p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header class="header">
  <nav class="navbar">
    <div class="desktopnav">
      <h2><%= link_to 'My Kuku', root_path, class: "navbar-brand"%></h2>
      <ul>
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: ""%>
        </li>|
        <li class="nav-item">
          <%= link_to "About Us", abouts_path, class: ""%>
        </li>|
        <li class="nav-item">
          <%= link_to "Contact us", contacts_path, class: ""%>
        </li>|
        <li class="nav-item">
          <%= link_to "Blogs", blogs_path, class: ""%>
        </li>|

        <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to "Chickens", chickens_path, class: ""%>
        </li>|

          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, class: 'nav-link', data: { turbo_method: :delete } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: ""%>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Kuku</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_importmap_tags %>
    <%# Linked the image preview JavaScript file %>
    <%= javascript_include_tag 'image_preview' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu+Condensed&display=swap" rel="stylesheet"> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <!-- Google fonts poppins, kaushan, Alkatra -->
    
    <link href="https://fonts.googleapis.com/css2?family=Alkatra:wght@400;500&family=Dancing+Script:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&family=Kaushan+Script&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <!--font aweome icons links-->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body class="h-100">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'layouts/navbar' %>
    <main class="main">
       <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>